trigger:
- main

variables:
  azureSubscription: 'azure-website-beesknee'

stages:
- stage: DeployToTesting
  jobs:
  - deployment: Deploy
    displayName: Deploy to Testing
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'testing'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az deployment group create --resource-group BeesKneeGroup --template-file ./test.bicep --parameters dnsNameLabel=beeskneeco-testing imageName=chumaigwe9/bees-knee-website:2.0'
