trigger:
- main

variables:
  azureSubscription: 'beeknees-website-service'

stages:
- stage: DeployToProduction
  jobs:
  - deployment: Deploy
    displayName: Deploy to Production
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az deployment group create --resource-group BeesKneeGroup --template-file main.bicep --parameters dnsNameLabel=beeskneeco imageName=chumaigwe9/bees-knee-website:2.0'
